name: PHP Tests

on: [push, pull_request]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # NC 28: PHP 8.0 - 8.3
          - php-versions: '8.0'
            nextcloud-versions: 'stable28'
          - php-versions: '8.1'
            nextcloud-versions: 'stable28'
          - php-versions: '8.2'
            nextcloud-versions: 'stable28'
          - php-versions: '8.3'
            nextcloud-versions: 'stable28'
          # NC 29: PHP 8.0 - 8.3
          - php-versions: '8.0'
            nextcloud-versions: 'stable29'
          - php-versions: '8.1'
            nextcloud-versions: 'stable29'
          - php-versions: '8.2'
            nextcloud-versions: 'stable29'
          - php-versions: '8.3'
            nextcloud-versions: 'stable29'
          # NC 30: PHP 8.1 - 8.3
          - php-versions: '8.1'
            nextcloud-versions: 'stable30'
          - php-versions: '8.2'
            nextcloud-versions: 'stable30'
          - php-versions: '8.3'
            nextcloud-versions: 'stable30'
          # NC 31: PHP 8.1 - 8.4
          - php-versions: '8.1'
            nextcloud-versions: 'stable31'
          - php-versions: '8.2'
            nextcloud-versions: 'stable31'
          - php-versions: '8.3'
            nextcloud-versions: 'stable31'
          - php-versions: '8.4'
            nextcloud-versions: 'stable31'
          # NC 32: PHP 8.1 - 8.4
          - php-versions: '8.1'
            nextcloud-versions: 'stable32'
          - php-versions: '8.2'
            nextcloud-versions: 'stable32'
          - php-versions: '8.3'
            nextcloud-versions: 'stable32'
          - php-versions: '8.4'
            nextcloud-versions: 'stable32'
          # NC 33: PHP 8.2 - 8.4
          - php-versions: '8.2'
            nextcloud-versions: 'stable33'
          - php-versions: '8.3'
            nextcloud-versions: 'stable33'
          - php-versions: '8.4'
            nextcloud-versions: 'stable33'

    name: php${{ matrix.php-versions }} on ${{ matrix.nextcloud-versions }} unit tests
    env:
      CI: true
      XDEBUG_MODE: coverage
    steps:
    - name: Set up php${{ matrix.php-versions }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: ctype, curl, dom, gd, gmp, iconv, intl, json, mbstring, openssl, pdo_sqlite, posix, sqlite, xml, zip
        coverage: xdebug
    - name: Checkout Nextcloud
      run: git clone https://github.com/nextcloud/server.git --recursive --depth 1 -b ${{ matrix.nextcloud-versions }} nextcloud
    - name: Install Nextcloud
      run: php -f nextcloud/occ maintenance:install --database-name oc_autotest --database-user oc_autotest --admin-user admin --admin-pass admin --database sqlite --database-pass=''
    - name: Checkout the app
      uses: actions/checkout@v6
      with:
        path: nextcloud/apps/sendent
    - name: Install dependencies
      working-directory: nextcloud/apps/sendent
      run: composer install --no-interaction
    - name: Enable app
      run: php -f nextcloud/occ app:enable sendent
    - name: Run tests
      working-directory: nextcloud/apps/sendent
      run: composer run test
